coin = float(input("Please, enter the number of mycoins you have: >"))
print("I will get", coin * 0.82, "ARS from the sale of", coin, "mycoins")
print("I will get", coin * 0.17, "HNL from the sale of", coin, "mycoins")
print("I will get", coin * 1.96, "AUD from the sale of", coin, "mycoins")
print("I will get", coin * 0.208, "MAD from the sale of", coin, "mycoins")
